apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: {{NAMESPACE}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: khareutkarsh/development-sample-webapp:jenkins_L20
        ports:
        - containerPort: 8080
